# Generated by Django 5.2.11 on 2026-02-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('code', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'alert_service_issue_types',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('domain_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_tracked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alert_service_routes',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('route_id', models.CharField(max_length=128, null=True)),
                ('domain_name', models.CharField(max_length=128, null=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('is_solved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='alert_service.issuetype')),
            ],
            options={
                'db_table': 'alert_service_issues',
            },
        ),
        migrations.CreateModel(
            name='NotificationReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_receivers', to='alert_service.issuetype')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_receivers', to='alert_service.route')),
            ],
            options={
                'db_table': 'alert_service_notification_receivers',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(max_length=128)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True)),
                ('update_status_attempts', models.SmallIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('warning_level', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='alert_service.route')),
            ],
            options={
                'db_table': 'alert_service_messages',
                'unique_together': {('exchange_id', 'route')},
            },
        ),
    ]
