# Generated by Django 5.2.11 on 2026-03-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0002_fesbrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fesbrequest',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
