# Generated by Django 5.2.11 on 2026-03-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0003_fesbrequest_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fesbrequest',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='fesbrequest',
            name='warning_level',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
