# Generated by Django 5.2.14 on 2026-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0004_remove_fesbrequest_is_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fesb_timezone', models.CharField(default='Europe/Moscow', max_length=128)),
                ('fesb_requests_check_interval', models.SmallIntegerField(default=15)),
                ('fesb_request_timeout', models.SmallIntegerField(default=60)),
                ('fesb_request_errors_threshold', models.SmallIntegerField(default=5)),
                ('fesb_messages_get_interval', models.SmallIntegerField(default=15)),
                ('fesb_messages_update_interval', models.SmallIntegerField(default=120)),
                ('fesb_messages_log_limit', models.SmallIntegerField(default=10)),
                ('fesb_messages_log_interval', models.SmallIntegerField(default=2)),
                ('fesb_single_route_errors_threshold', models.SmallIntegerField(default=3)),
                ('fesb_routes_errors_threshold', models.SmallIntegerField(default=2)),
                ('fesb_domain_errors_threshold', models.SmallIntegerField(default=2)),
                ('fesb_status_update_attempts', models.SmallIntegerField(default=3)),
                ('db_timeout', models.SmallIntegerField(default=30)),
                ('messages_check_warning_interval', models.SmallIntegerField(default=30)),
                ('auto_track_new_routes', models.BooleanField(default=True)),
                ('issues_check_interval', models.SmallIntegerField(default=15)),
                ('admin_email', models.CharField(max_length=128)),
                ('inform_admin_if_no_receivers', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alert_service_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='only_one_settings_row')],
            },
        ),
    ]
