# Generated by Django 5.2.14 on 2026-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0005_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='admin_email',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
