# Generated by Django 5.2.14 on 2026-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0006_alter_systemsettings_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_delay',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='inform_admin_if_no_receivers',
            field=models.BooleanField(default=False),
        ),
    ]
