# Generated by Django 5.2.15 on 2026-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0007_systemsettings_smtp_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
