# Generated by Django 5.2.15 on 2026-06-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0008_message_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='fesbrequest',
            name='type',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
