# Generated by Django 5.2.15 on 2026-06-09 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0009_fesbrequest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FesbRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alert_service_fesb_request_types',
            },
        ),
        migrations.AlterField(
            model_name='fesbrequest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='alert_service.fesbrequesttype'),
        ),
    ]
