# Generated by Django 5.2.15 on 2026-06-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0010_fesbrequesttype_alter_fesbrequest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fesbrequesttype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fesbrequesttype',
            name='updated_at',
        ),
    ]
