# Generated by Django 5.2.17 on 2026-08-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0011_remove_fesbrequesttype_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetype',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('DOMAIN', 'Domain'), ('ROUTE', 'Route')], default='GLOBAL', max_length=16),
        ),
    ]
