# Generated by Django 5.2.17 on 2026-08-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0012_issuetype_scope'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificationreceiver',
            constraint=models.CheckConstraint(condition=models.Q(('route__isnull', True), ('domain_name__isnull', True), _connector='OR'), name='notification_receiver_not_route_and_domain'),
        ),
        migrations.AddConstraint(
            model_name='notificationreceiver',
            constraint=models.UniqueConstraint(fields=('email', 'issue_type', 'route', 'domain_name'), name='unique_notification_receiver_rule', nulls_distinct=False),
        ),
    ]
