# Generated by Django 5.2.17 on 2026-08-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0013_notificationreceiver_notification_receiver_not_route_and_domain_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fesbrequest',
            index=models.Index(fields=['created_at'], name='fesb_req_created_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['created_at'], name='issue_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['start_date'], name='msg_start_idx'),
        ),
    ]
