# Generated by Django 5.2.17 on 2026-08-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_service', '0014_fesbrequest_fesb_req_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='is_notified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
